# ===============================
# Nome da aplicação
# ===============================
spring.application.name=gestpro-backend

# ===============================
# Perfil ativo
# ===============================
spring.profiles.active=dev

# ===============================
# Configurações do servidor
# ===============================
server.port=8080

# ===============================
# Swagger (Springdoc OpenAPI)
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# JWT secret key
jwt.secret=GestProChaveExtremamenteDificilSecuraSJMDFGX123!


#Criar sua própria autenticação com JWT e banco de dados
spring.security.user.name=Martins
spring.security.user.password=5517
spring.security.user.roles=ADMIN



#OpenAPI
#futuramente
#spring.ai.azure.openai.endpoint=https://<seu-endpoint>.openai.azure.com/
#spring.ai.azure.openai.key=<sua-chave-de-acesso>
#spring.ai.azure.openai.deployment=<nome-do-deployment>


